site_name: 'trip'
pages:
- '主页': 'index.md'
- '用户指南':
    - '简介': 'user/intro.md'
    - '安装Trip': 'user/install.md'
    - '快速开始': 'user/quickstart.md'
#- 'API列表': 'api.md'
#- 'FAQ': 'FAQ.md'
# extra_css: ['docs/bootstrap/css']
# extra_javascript: ['docs/bootstrap/js']
# theme_dir: 'docs/bootstrap'
repo_url: 'https://github.com/littlecodersh/trip'
